name: Vulnerability Check

on:
  schedule:
    - cron: "0 6 */2 * *"   # Run every 2 days at 6 am
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: [ubuntu-latest]
    name: Security Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Security scan
        uses: canonical/comsys-build-tools/.github/actions/security-scan-upload@main
        with: 
          upload-github-security: true
          upload-sarif-artifact: true